name: CoinAPI
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for coin data
    defaultValue: coin-data
    required: true
  - name: coin_api_key
    inputType: HiddenText
    description: Your Coin API key
    defaultValue: 9421CC64-B9D2-49D4-B075-0D4513374588
    required: true
  - name: primary_currency
    inputType: FreeText
    description: This is the main currency of interest
    defaultValue: BTC
    required: true
  - name: secondary_currencies
    inputType: FreeText
    description: These are the currencies to compare the primary currency to
    defaultValue: USD,GBP
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: quix_functions.py
