name: StatGenerator
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: ''
    defaultValue: generic-stat
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
