name: StatGenerator
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: ''
    defaultValue: generic-stat
    required: true
  - name: topic_name
    inputType: FreeText
    description: ''
    defaultValue: testtopic
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
