name: StatGenerator
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: ''
    defaultValue: generic-stat
    required: true
  - name: topics
    inputType: FreeText
    description: ''
    defaultValue: '[     {         "topic_name": "some topic 1"     },     {         "topic_name": "some topic 2"     } ]'
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
